language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
    - ~/.cache
  yarn: true
script:
  - yarn run build
  - yarn run serve &
  - yarn run test
  - kill $(jobs -p) || true
