version: "3.3"

services:
  web:
    build: .
    command: yarn _start
    volumes:
      - ./src:/usr/src/app/src
      - ./docs:/usr/src/app/docs
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
    ports:
      - 8000:8000

  selenium-hub:
    image: selenium/hub:3.6
    ports:
      - 4444:4444
    environment:
      - GRID_BROWSER_TIMEOUT=30000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=30000
      - GRID_MAX_SESSION=2

  selenium-node-chrome:
    image: selenium/node-chrome:3.6
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  selenium-node-firefox:
    image: selenium/node-firefox:3.4
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
